services:
  www:
    image: ghcr.io/soruly/trace.moe-www:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
    ports:
      - ${WWW_PORT}:3000
    networks:
      trace_moe_net:

  api:
    image: ghcr.io/soruly/trace.moe-api:latest
    depends_on:
      - liresolr
    restart: unless-stopped
    environment:
      - VIDEO_PATH=/app/video/
      - HASH_PATH=/app/hash/
      - TRACE_API_SALT=${TRACE_API_SALT}
      - TRACE_ACCURACY=${TRACE_ACCURACY}
      - MAX_WORKER=${MAX_WORKER}
      # - MEDIA_QUEUE=${MEDIA_QUEUE}
      # - SEARCH_QUEUE=${SEARCH_QUEUE}
      # - USE_IMAGE_PROXY=${USE_IMAGE_PROXY}
      - SOLA_SOLR_LIST=http://172.17.0.1:${SOLR_PORT}/solr/
      - SOLA_SOLR_SIZE=1
      - SERVER_PORT=3000
    ports:
      - ${API_PORT}:3000
    volumes:
      - type: bind
        source: ${DB_PATH}
        target: /app/db
      - type: bind
        source: ${VIDEO_PATH}
        target: /app/video/
      - type: bind
        source: ${HASH_PATH}
        target: /app/hash/
    networks:
      trace_moe_net:

  liresolr:
    image: ghcr.io/soruly/liresolr:latest
    command: solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
    restart: unless-stopped
    environment:
      - SOLR_HEAP=${SOLR_HEAP}
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - type: bind
        source: ${SOLR_DIR}
        target: /var/solr
    networks:
      trace_moe_net:

networks:
  trace_moe_net:
    driver: bridge
